# Site settings
title: Code Panda
description: > # this means to ignore newlines until "baseurl:"
  The personal site and blog of Evan Sheffield.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://evsheffield.github.io" # the base hostname & protocol for your site
github_username:  evsheffield
linkedin_url: "https://www.linkedin.com/pub/evan-sheffield/27/95a/7a4"

# Build settings
markdown: kramdown

highlighter: pygment
